model_name: google/mobilenet_v2_1.0_224
lr: 0.0001
task: "regression"
in_chans: 4
mean: [0.1048, 0.0189, 0.1048, 0.0189]
std: [0.8203, 0.0758, 0.8203, 0.0758]
regression_loss: "MAE+MSE"
regression_loss_coefficients: [1, 1]
classification_loss_coefficient: 0.0001
